services:
  development:
    image: ffxiv-history
    build: .
    command: sleep infinity
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    ports:
      - '3000:3000'
    restart: unless-stopped
